name: Publish Package

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package.json name via Bash
        run: |
          echo "🔧 Updating package name..."
          sed -i 's/"name": "bills"/"name": "@mockholm\/bills"/' package.json
          echo "✅ package.json name updated to @mockholm/bills"

      - name: Setup Node.js v23.11.0
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run compile

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}